services:
  - type: web
    name: kreater-backend
    root: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://kreator-io-web.vercel.app
      - key: RECAPTCHA_BYPASS
        value: false
